version: "3.9"

services:
  java-maven:
    image: maven:3.9.6-eclipse-temurin-11
    container_name: dremio_clickhouse_dev
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - maven-cache:/root/.m2
    command: mvn clean install

volumes:
  maven-cache:
